### ISSUE TITLE
Highlight missing on simple UPDATE query

### ISSUE THREAD

**Issue by rcardoso20** [gbprod/php-enhanced-treesitter.nvim#10]
Hello.

There is no highlight for the following query:
```php
UPDATE table_name SET column = 'value' WHERE column = 'value'
``` 
This happens because the UPDATE injection is expecting the "FROM" keyword, which is not required on the "UPDATE" statement.
I think it might be as simple as removing the "FROM" keyword from the "UPDATE" statement.

By the way, great job on the plugin/query injection, very helpful.

**Comment by gbprod** [comment]
Fixed !
Thanks
