### ISSUE TITLE
feature request - inject printf grammar

### ISSUE THREAD

**Issue by fbuchlak** [gbprod/php-enhanced-treesitter.nvim#13]
Would you consider adding [printf](https://github.com/tree-sitter-grammars/tree-sitter-printf) grammar? Or is it out of scope for this project? I've been using this snippet for a while and it was pretty helpful.

Currently I'm using
```
; extends

((function_call_expression
  function: (_) @_printf_func_identifier
  arguments:
    (arguments
      .
      (argument
        (_
          (string_content) @injection.content))))
  (#set! injection.language "printf")
  (#any-of? @_printf_func_identifier
    "fprintf" "printf" "sprintf" "vfprintf" "vprintf" "vsprintf"))
```
![2024-05-20-13:21:25](https://github.com/gbprod/php-enhanced-treesitter.nvim/assets/30214087/8b3c8c45-1356-495f-b721-5840c2fa9a02)

**Comment by gbprod** [comment]
Oh yes, that's interesting, you can open a PR! I think you can also open a PR on nvim-treesitter, they might be interested.

**Comment by gbprod** [comment]
Done here : https://github.com/gbprod/php-enhanced-treesitter.nvim/commit/9b12cc71616729aabb53b71bce24588d03554de2

I will create a PR in nvim-treesitter

**Comment by fbuchlak** [comment]
> Done here : [9b12cc7](https://github.com/gbprod/php-enhanced-treesitter.nvim/commit/9b12cc71616729aabb53b71bce24588d03554de2)
> 
> I will create a PR in nvim-treesitter

thanks, didn't have much time
