### ISSUE TITLE
Variable Reference in string SQL Query Breaks Highlighting

### ISSUE THREAD

**Issue by jthemenace** [gbprod/php-enhanced-treesitter.nvim#3]
Thank you for the work you've done on this plugin.  

The main PHP code base I work in has a ton of SQL queries in strings.  I've noticed while using this plugin, the SQL syntax highlighting inside of those strings works great, except for when a variable is used in that string.  In that case, the highlighting stops for every character after that variable reference.  Not sure if that would need to be fixed with the injection in this plugin or on the Tree-Sitter SQL side.  Let me know if you have any ideas on how to get around this.  I have attached a screen shot of one very small query that has this issue.

<img width="721" alt="Screenshot 2023-03-01 at 10 57 31 AM" src="https://user-images.githubusercontent.com/9721406/222194106-9a221cc4-d92f-44f3-8d5f-72d579cc6552.png">

**Comment by gbprod** [comment]
Hey!
I've pushed a fix that should do the trick, can you update and try again and give me some feedback ?
Thanks !

**Comment by jthemenace** [comment]
Thank you for working on this.  Unfortunately, with the update the highlighting is still stopping after the variable reference.

**Comment by kedodrill** [comment]
@gbprod this has been closed for awhile, but I'm having this problem. seems like you switched over to using some new syntax from treesitter and exclude children didn't make it over. Do you have any links to documentation on the syntax? I want to try and help out here...looks like nvim-treesitter doesn't want html injection in php so I thought I would try to figure that out.

Also, we use postgres at work and I found that the `WITH` injection query doesn't work just by using `@sql`. It needs `@injection.content`.

```
(encapsed_string (string_value) @injection.content
    (#set! injection.language "sql")
    (#set! injection.include-children)
    (#lua-match? @injection.content "^%s*[Ww][Ii][Tt][Hh]"))
``` 

I can make a PR if you'd like.

EDIT: worked out a simple injection scheme for html and I can make a PR for that too if you want.

**Comment by gbprod** [comment]
I am currently on vacation, I will take the time to respond to you when I come back 😉

**Comment by gbprod** [comment]
> @gbprod this has been closed for awhile, but I'm having this problem. seems like you switched over to using some new syntax from treesitter and exclude children didn't make it over. Do you have any links to documentation on the syntax? I want to try and help out here...looks like nvim-treesitter doesn't want html injection in php so I thought I would try to figure that out.

I'm aware of this issue... I will make some test with latest version to see if I can do someting...

> Also, we use postgres at work and I found that the `WITH` injection query doesn't work just by using `@sql`. It needs `@injection.content`.
> 
> ```
> (encapsed_string (string_value) @injection.content
>     (#set! injection.language "sql")
>     (#set! injection.include-children)
>     (#lua-match? @injection.content "^%s*[Ww][Ii][Tt][Hh]"))
> ```
> 
> I can make a PR if you'd like.

Oh you're right, I'll fix it soon


> EDIT: worked out a simple injection scheme for html and I can make a PR for that too if you want.

Feel free to open a PR, you're welcome ;)
